// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"log"
	"sync"

	"github.com/crhntr/resource"
	"github.com/crhntr/resource/internal/example"
)

type Get struct {
	Stub        func(context.Context, *log.Logger, example.Resource, example.GetParams, example.Version, string) ([]resource.MetadataField, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 context.Context
		arg2 *log.Logger
		arg3 example.Resource
		arg4 example.GetParams
		arg5 example.Version
		arg6 string
	}
	returns struct {
		result1 []resource.MetadataField
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 []resource.MetadataField
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Get) Spy(arg1 context.Context, arg2 *log.Logger, arg3 example.Resource, arg4 example.GetParams, arg5 example.Version, arg6 string) ([]resource.MetadataField, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 context.Context
		arg2 *log.Logger
		arg3 example.Resource
		arg4 example.GetParams
		arg5 example.Version
		arg6 string
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("getFunc", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return returns.result1, returns.result2
}

func (fake *Get) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *Get) Calls(stub func(context.Context, *log.Logger, example.Resource, example.GetParams, example.Version, string) ([]resource.MetadataField, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *Get) ArgsForCall(i int) (context.Context, *log.Logger, example.Resource, example.GetParams, example.Version, string) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2, fake.argsForCall[i].arg3, fake.argsForCall[i].arg4, fake.argsForCall[i].arg5, fake.argsForCall[i].arg6
}

func (fake *Get) Returns(result1 []resource.MetadataField, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 []resource.MetadataField
		result2 error
	}{result1, result2}
}

func (fake *Get) ReturnsOnCall(i int, result1 []resource.MetadataField, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 []resource.MetadataField
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 []resource.MetadataField
		result2 error
	}{result1, result2}
}

func (fake *Get) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Get) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
