// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"log"
	"sync"

	"github.com/crhntr/resource/internal/example"
)

type Check struct {
	Stub        func(context.Context, example.Resource, example.Version, *log.Logger) ([]example.Version, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 context.Context
		arg2 example.Resource
		arg3 example.Version
		arg4 *log.Logger
	}
	returns struct {
		result1 []example.Version
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 []example.Version
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Check) Spy(arg1 context.Context, arg2 example.Resource, arg3 example.Version, arg4 *log.Logger) ([]example.Version, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 context.Context
		arg2 example.Resource
		arg3 example.Version
		arg4 *log.Logger
	}{arg1, arg2, arg3, arg4})
	stub := fake.Stub
	returns := fake.returns
	fake.recordInvocation("checkFunc", []interface{}{arg1, arg2, arg3, arg4})
	fake.mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return returns.result1, returns.result2
}

func (fake *Check) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *Check) Calls(stub func(context.Context, example.Resource, example.Version, *log.Logger) ([]example.Version, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *Check) ArgsForCall(i int) (context.Context, example.Resource, example.Version, *log.Logger) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2, fake.argsForCall[i].arg3, fake.argsForCall[i].arg4
}

func (fake *Check) Returns(result1 []example.Version, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 []example.Version
		result2 error
	}{result1, result2}
}

func (fake *Check) ReturnsOnCall(i int, result1 []example.Version, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 []example.Version
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 []example.Version
		result2 error
	}{result1, result2}
}

func (fake *Check) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Check) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
